SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[LogPrice](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Amount] [varchar](50) NOT NULL,
	[ModifiedBy] [varchar](50) NOT NULL,
	[Modified] [datetime2](7) NOT NULL,
	[CreatedBy] [varchar](50) NOT NULL,
	[Created] [datetime2](7) NOT NULL,
 CONSTRAINT [PK_LogPrice] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


